### ISSUE TITLE
怎么也不自动查询快递信息 然后去设置 打开自动查询出来后再进去又自动自动关上了 

### ISSUE THREAD

**Issue by on6hz** [minosss/express-plus#14]
快递助手 19.10.12.1037
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

**Comment by wsltshh** [comment]
我的倒是不自动关闭，但是也不能自动查询
快递助手 20.1.17.639
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Cent Browser
版本 4.1.7.182（正式版本） （64 位） (Chromium 78.0.3904.108)

**Comment by minosss** [comment]
自动查询 20.1.17 是有跑的了
不过不知道是不是 Chrome (76开始) 的 SameSite 功能，导致 background 页面请求的时候无法用kuaidi100 的 cookies，然后接口返回不到数据，可是操作页面 popup 却可以调用到接口

**Comment by wsltshh** [comment]
> 自动查询20.1.17是有跑的了
> 不过不过不知道是不是Chrome（76开始）的SameSite功能，导致背景页面请求的时候无法用kuaidi100的cookie，然后接口返回不到数据，可是操作页面popup却可以调用到接口

你可是开发者呀😆有空的话加油修复下。
现在快递各种慢，老想刷快递，有自动查询就省事了
