### ISSUE TITLE
查不了快递了

### ISSUE THREAD

**Issue by willie91** [minosss/express-plus#5]
![default](https://user-images.githubusercontent.com/32695308/53854715-87de0780-4005-11e9-8087-63561fcb33fd.jpg)
麻烦作者看下

**Comment by minosss** [comment]
更新完应该ok了

**Comment by willie91** [comment]
> 更新完应该OK了

![default](https://user-images.githubusercontent.com/32695308/53880194-5ab44800-404b-11e9-9267-77aacc8272ef.jpg)
刚刚更新完

**Comment by minosss** [comment]
@willie91 用第一个 `huitongkuaidi`
官网也是

`huitongkuaidi` -> 百世快递
`baishiwuliu` -> 百世快运
