### ISSUE TITLE
19.3.12更新版本无法查询快递

### ISSUE THREAD

**Issue by woxinyi248** [minosss/express-plus#6]
![image](https://user-images.githubusercontent.com/16396597/54370893-64752580-46b3-11e9-8fe0-21a3f05dc6e1.png)
无法跳转出选择项

**Comment by minosss** [comment]
无法识别的去 选择快递 界面点快递类型

**Comment by woxinyi248** [comment]
> 无法识别的去选择快递界面点快递类型
![image](https://user-images.githubusercontent.com/16396597/54407675-b486d300-4719-11e9-8010-a9bb0fbd1550.png)
快递公司参数异常：单号不存在或者已经过期

**Comment by minosss** [comment]
kuaidi100的接口问题~  baidu那边应该是有另外的请求方式~  会尝试添加baidu的请求方式作为备选

**Comment by minosss** [comment]
19.3.15.843 版本已更新，添加了 baidu 的请求接口作为备选，这个单号测试没问题，有问题再打开这个问题
