### ISSUE TITLE
EDGE中无法使用 版本115.0.1901.200

### ISSUE THREAD

**Issue by adamp4** [minosss/express-plus#69]
你好，插件非常好，但在edge中查询所有单号无记录
edge版本115.0.1901.200
希望能在edge中使用，感谢你分享这么棒的插件！

**Comment by minosss** [comment]
试了下edge是可以的

**Comment by adamp4** [comment]
![image](https://github.com/minosss/express-plus/assets/44283910/9798476a-c3d1-40c3-ad9a-6820069152f0)
![image](https://github.com/minosss/express-plus/assets/44283910/d2050afd-4329-4a0e-b3c5-5ff40c3907c9)
